name = "ewdev/attempt"
version = "0.0.0"
description = "A simple library for doing retry logic"
authors = ["EwDev (https://ewdev.net/)"]
repository = "https://github.com/ewd3v/luau_attempt"
license = "MIT"
includes = ["src/**", "pesde.toml", "LICENSE", "README.md"]

[engines]
pesde = "^0.7.0"
lune = "^0.10.4" # Required for build script even though we're running it via `pesde x`, probably a bug with pesde

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
analyze = "scripts/analyze.luau"
build = "scripts/build.luau"
format_check = "scripts/format_check.luau"
# test = "scripts/test.luau"
test = "tests/init.luau" # Current workaround for multitarget not including dev dependencies

[dev_dependencies]
multitarget = { name = "ewdev/multitarget", version = "=0.4.2-rc.7", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.3.1", target = "lune" }
luau-lsp = { name = "pesde/luau_lsp", version = "^1.56.2", target = "lune" }
selene = { name = "pesde/selene", version = "^0.29.0+toolchainlib.1", target = "lune" }
darklua = { name = "pesde/darklua", version = "^0.17.2", target = "lune" }
tiniest = { name = "ewdev/tiniest", version = "=0.0.0-20251120T191744Z", target = "lune" }